apiVersion: apps/v1
kind: Deployment
metadata:
  name: config
  labels:
    app: config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config
  template:
    metadata:
      labels:
        app: config
    spec:
      containers:
      - name: config
        image: 192.168.1.104:5000/sample-1:v1.0.0-2
        command: [ "/usr/bin/app", "config", "store:8000" ]
