apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetcher
  labels:
    app: fetcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fetcher
  template:
    metadata:
      labels:
        app: fetcher
    spec:
      containers:
      - name: fetcher
        image: 192.168.1.104:5000/sample-1:v1.0.0-2
        command: [ "/usr/bin/app", "fetcher", "config:8000" ]
