// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config.proto

package common

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Nil is nil
type Nil struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nil) Reset()         { *m = Nil{} }
func (m *Nil) String() string { return proto.CompactTextString(m) }
func (*Nil) ProtoMessage()    {}
func (*Nil) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{0}
}

func (m *Nil) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nil.Unmarshal(m, b)
}
func (m *Nil) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nil.Marshal(b, m, deterministic)
}
func (m *Nil) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nil.Merge(m, src)
}
func (m *Nil) XXX_Size() int {
	return xxx_messageInfo_Nil.Size(m)
}
func (m *Nil) XXX_DiscardUnknown() {
	xxx_messageInfo_Nil.DiscardUnknown(m)
}

var xxx_messageInfo_Nil proto.InternalMessageInfo

// ServeWork is a collection of data sources
type ServeWork struct {
	Feeds                []*ServeFeed `protobuf:"bytes,1,rep,name=feeds,proto3" json:"feeds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ServeWork) Reset()         { *m = ServeWork{} }
func (m *ServeWork) String() string { return proto.CompactTextString(m) }
func (*ServeWork) ProtoMessage()    {}
func (*ServeWork) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{1}
}

func (m *ServeWork) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServeWork.Unmarshal(m, b)
}
func (m *ServeWork) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServeWork.Marshal(b, m, deterministic)
}
func (m *ServeWork) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServeWork.Merge(m, src)
}
func (m *ServeWork) XXX_Size() int {
	return xxx_messageInfo_ServeWork.Size(m)
}
func (m *ServeWork) XXX_DiscardUnknown() {
	xxx_messageInfo_ServeWork.DiscardUnknown(m)
}

var xxx_messageInfo_ServeWork proto.InternalMessageInfo

func (m *ServeWork) GetFeeds() []*ServeFeed {
	if m != nil {
		return m.Feeds
	}
	return nil
}

// ServeFeed defines a remote data source
type ServeFeed struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Store                string   `protobuf:"bytes,3,opt,name=store,proto3" json:"store,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServeFeed) Reset()         { *m = ServeFeed{} }
func (m *ServeFeed) String() string { return proto.CompactTextString(m) }
func (*ServeFeed) ProtoMessage()    {}
func (*ServeFeed) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{2}
}

func (m *ServeFeed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServeFeed.Unmarshal(m, b)
}
func (m *ServeFeed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServeFeed.Marshal(b, m, deterministic)
}
func (m *ServeFeed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServeFeed.Merge(m, src)
}
func (m *ServeFeed) XXX_Size() int {
	return xxx_messageInfo_ServeFeed.Size(m)
}
func (m *ServeFeed) XXX_DiscardUnknown() {
	xxx_messageInfo_ServeFeed.DiscardUnknown(m)
}

var xxx_messageInfo_ServeFeed proto.InternalMessageInfo

func (m *ServeFeed) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ServeFeed) GetStore() string {
	if m != nil {
		return m.Store
	}
	return ""
}

// FetchWork tells a fetcher all its jobs.
type FetchWork struct {
	Jobs                 []*FetchJob `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *FetchWork) Reset()         { *m = FetchWork{} }
func (m *FetchWork) String() string { return proto.CompactTextString(m) }
func (*FetchWork) ProtoMessage()    {}
func (*FetchWork) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{3}
}

func (m *FetchWork) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchWork.Unmarshal(m, b)
}
func (m *FetchWork) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchWork.Marshal(b, m, deterministic)
}
func (m *FetchWork) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchWork.Merge(m, src)
}
func (m *FetchWork) XXX_Size() int {
	return xxx_messageInfo_FetchWork.Size(m)
}
func (m *FetchWork) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchWork.DiscardUnknown(m)
}

var xxx_messageInfo_FetchWork proto.InternalMessageInfo

func (m *FetchWork) GetJobs() []*FetchJob {
	if m != nil {
		return m.Jobs
	}
	return nil
}

// FetchJob tells a fetcher to do something.
type FetchJob struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	URL                  string   `protobuf:"bytes,2,opt,name=URL,proto3" json:"URL,omitempty"`
	Store                string   `protobuf:"bytes,3,opt,name=store,proto3" json:"store,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchJob) Reset()         { *m = FetchJob{} }
func (m *FetchJob) String() string { return proto.CompactTextString(m) }
func (*FetchJob) ProtoMessage()    {}
func (*FetchJob) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{4}
}

func (m *FetchJob) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchJob.Unmarshal(m, b)
}
func (m *FetchJob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchJob.Marshal(b, m, deterministic)
}
func (m *FetchJob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchJob.Merge(m, src)
}
func (m *FetchJob) XXX_Size() int {
	return xxx_messageInfo_FetchJob.Size(m)
}
func (m *FetchJob) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchJob.DiscardUnknown(m)
}

var xxx_messageInfo_FetchJob proto.InternalMessageInfo

func (m *FetchJob) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *FetchJob) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func (m *FetchJob) GetStore() string {
	if m != nil {
		return m.Store
	}
	return ""
}

func init() {
	proto.RegisterType((*Nil)(nil), "common.Nil")
	proto.RegisterType((*ServeWork)(nil), "common.ServeWork")
	proto.RegisterType((*ServeFeed)(nil), "common.ServeFeed")
	proto.RegisterType((*FetchWork)(nil), "common.FetchWork")
	proto.RegisterType((*FetchJob)(nil), "common.FetchJob")
}

func init() { proto.RegisterFile("config.proto", fileDescriptor_3eaf2c85e69e9ea4) }

var fileDescriptor_3eaf2c85e69e9ea4 = []byte{
	// 228 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0x4b,
	0xcb, 0x4c, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4b, 0xce, 0xcf, 0xcd, 0xcd, 0xcf,
	0x53, 0x62, 0xe5, 0x62, 0xf6, 0xcb, 0xcc, 0x51, 0x32, 0xe1, 0xe2, 0x0c, 0x4e, 0x2d, 0x2a, 0x4b,
	0x0d, 0xcf, 0x2f, 0xca, 0x16, 0x52, 0xe7, 0x62, 0x4d, 0x4b, 0x4d, 0x4d, 0x29, 0x96, 0x60, 0x54,
	0x60, 0xd6, 0xe0, 0x36, 0x12, 0xd4, 0x83, 0xa8, 0xd5, 0x03, 0xab, 0x70, 0x4b, 0x4d, 0x4d, 0x09,
	0x82, 0xc8, 0x2b, 0x19, 0x42, 0x75, 0x81, 0xc4, 0x84, 0xf8, 0xb8, 0x98, 0x3c, 0x5d, 0x24, 0x18,
	0x15, 0x18, 0x35, 0x38, 0x83, 0x98, 0x3c, 0x5d, 0x84, 0x44, 0xb8, 0x58, 0x8b, 0x4b, 0xf2, 0x8b,
	0x52, 0x25, 0x98, 0xc1, 0x42, 0x10, 0x0e, 0x48, 0x8b, 0x5b, 0x6a, 0x49, 0x72, 0x06, 0xd8, 0x22,
	0x15, 0x2e, 0x96, 0xac, 0xfc, 0x24, 0x98, 0x3d, 0x02, 0x30, 0x7b, 0xc0, 0x0a, 0xbc, 0xf2, 0x93,
	0x82, 0xc0, 0xb2, 0x4a, 0x4e, 0x5c, 0x1c, 0x30, 0x11, 0x0c, 0x4b, 0x04, 0xb8, 0x98, 0x43, 0x83,
	0x7c, 0x24, 0x98, 0xc0, 0x02, 0x20, 0x26, 0x76, 0x6b, 0x8d, 0x72, 0xb8, 0xd8, 0x9c, 0xc1, 0xde,
	0x17, 0x32, 0xe0, 0xe2, 0x71, 0x4f, 0x2d, 0x41, 0x78, 0x96, 0x1b, 0x66, 0xab, 0x5f, 0x66, 0x8e,
	0x14, 0xaa, 0x57, 0x41, 0xf2, 0x4a, 0x0c, 0x50, 0x1d, 0x08, 0x57, 0x63, 0xd7, 0x01, 0x97, 0x57,
	0x62, 0x48, 0x62, 0x03, 0x87, 0xb1, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x6e, 0xc4, 0xf3, 0x69,
	0x73, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ConfigClient is the client API for Config service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConfigClient interface {
	GetServeWork(ctx context.Context, in *Nil, opts ...grpc.CallOption) (*ServeWork, error)
	GetFetchWork(ctx context.Context, in *Nil, opts ...grpc.CallOption) (*FetchWork, error)
}

type configClient struct {
	cc *grpc.ClientConn
}

func NewConfigClient(cc *grpc.ClientConn) ConfigClient {
	return &configClient{cc}
}

func (c *configClient) GetServeWork(ctx context.Context, in *Nil, opts ...grpc.CallOption) (*ServeWork, error) {
	out := new(ServeWork)
	err := c.cc.Invoke(ctx, "/common.Config/GetServeWork", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configClient) GetFetchWork(ctx context.Context, in *Nil, opts ...grpc.CallOption) (*FetchWork, error) {
	out := new(FetchWork)
	err := c.cc.Invoke(ctx, "/common.Config/GetFetchWork", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigServer is the server API for Config service.
type ConfigServer interface {
	GetServeWork(context.Context, *Nil) (*ServeWork, error)
	GetFetchWork(context.Context, *Nil) (*FetchWork, error)
}

// UnimplementedConfigServer can be embedded to have forward compatible implementations.
type UnimplementedConfigServer struct {
}

func (*UnimplementedConfigServer) GetServeWork(ctx context.Context, req *Nil) (*ServeWork, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServeWork not implemented")
}
func (*UnimplementedConfigServer) GetFetchWork(ctx context.Context, req *Nil) (*FetchWork, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFetchWork not implemented")
}

func RegisterConfigServer(s *grpc.Server, srv ConfigServer) {
	s.RegisterService(&_Config_serviceDesc, srv)
}

func _Config_GetServeWork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Nil)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServer).GetServeWork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.Config/GetServeWork",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServer).GetServeWork(ctx, req.(*Nil))
	}
	return interceptor(ctx, in, info, handler)
}

func _Config_GetFetchWork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Nil)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServer).GetFetchWork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.Config/GetFetchWork",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServer).GetFetchWork(ctx, req.(*Nil))
	}
	return interceptor(ctx, in, info, handler)
}

var _Config_serviceDesc = grpc.ServiceDesc{
	ServiceName: "common.Config",
	HandlerType: (*ConfigServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetServeWork",
			Handler:    _Config_GetServeWork_Handler,
		},
		{
			MethodName: "GetFetchWork",
			Handler:    _Config_GetFetchWork_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "config.proto",
}
