// Code generated by protoc-gen-go. DO NOT EDIT.
// source: store.proto

package common

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// StoreArticle is an article in the store
type StoreArticle struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Date                 int64    `protobuf:"varint,3,opt,name=date,proto3" json:"date,omitempty"`
	Body                 string   `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreArticle) Reset()         { *m = StoreArticle{} }
func (m *StoreArticle) String() string { return proto.CompactTextString(m) }
func (*StoreArticle) ProtoMessage()    {}
func (*StoreArticle) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{0}
}

func (m *StoreArticle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreArticle.Unmarshal(m, b)
}
func (m *StoreArticle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreArticle.Marshal(b, m, deterministic)
}
func (m *StoreArticle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreArticle.Merge(m, src)
}
func (m *StoreArticle) XXX_Size() int {
	return xxx_messageInfo_StoreArticle.Size(m)
}
func (m *StoreArticle) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreArticle.DiscardUnknown(m)
}

var xxx_messageInfo_StoreArticle proto.InternalMessageInfo

func (m *StoreArticle) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *StoreArticle) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *StoreArticle) GetDate() int64 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *StoreArticle) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

// StorePostFeedRequest is how to put articles into the store
type StorePostFeedRequest struct {
	FeedID               string          `protobuf:"bytes,1,opt,name=feedID,proto3" json:"feedID,omitempty"`
	Articles             []*StoreArticle `protobuf:"bytes,2,rep,name=articles,proto3" json:"articles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *StorePostFeedRequest) Reset()         { *m = StorePostFeedRequest{} }
func (m *StorePostFeedRequest) String() string { return proto.CompactTextString(m) }
func (*StorePostFeedRequest) ProtoMessage()    {}
func (*StorePostFeedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{1}
}

func (m *StorePostFeedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorePostFeedRequest.Unmarshal(m, b)
}
func (m *StorePostFeedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorePostFeedRequest.Marshal(b, m, deterministic)
}
func (m *StorePostFeedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorePostFeedRequest.Merge(m, src)
}
func (m *StorePostFeedRequest) XXX_Size() int {
	return xxx_messageInfo_StorePostFeedRequest.Size(m)
}
func (m *StorePostFeedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StorePostFeedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StorePostFeedRequest proto.InternalMessageInfo

func (m *StorePostFeedRequest) GetFeedID() string {
	if m != nil {
		return m.FeedID
	}
	return ""
}

func (m *StorePostFeedRequest) GetArticles() []*StoreArticle {
	if m != nil {
		return m.Articles
	}
	return nil
}

// StorePostFeedResponse is nothing
type StorePostFeedResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorePostFeedResponse) Reset()         { *m = StorePostFeedResponse{} }
func (m *StorePostFeedResponse) String() string { return proto.CompactTextString(m) }
func (*StorePostFeedResponse) ProtoMessage()    {}
func (*StorePostFeedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{2}
}

func (m *StorePostFeedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorePostFeedResponse.Unmarshal(m, b)
}
func (m *StorePostFeedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorePostFeedResponse.Marshal(b, m, deterministic)
}
func (m *StorePostFeedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorePostFeedResponse.Merge(m, src)
}
func (m *StorePostFeedResponse) XXX_Size() int {
	return xxx_messageInfo_StorePostFeedResponse.Size(m)
}
func (m *StorePostFeedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StorePostFeedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StorePostFeedResponse proto.InternalMessageInfo

// StoreGetFeedRequest is how to request articles from the store
type StoreGetFeedRequest struct {
	FeedID               string   `protobuf:"bytes,1,opt,name=feedID,proto3" json:"feedID,omitempty"`
	Since                int64    `protobuf:"varint,2,opt,name=since,proto3" json:"since,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreGetFeedRequest) Reset()         { *m = StoreGetFeedRequest{} }
func (m *StoreGetFeedRequest) String() string { return proto.CompactTextString(m) }
func (*StoreGetFeedRequest) ProtoMessage()    {}
func (*StoreGetFeedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{3}
}

func (m *StoreGetFeedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreGetFeedRequest.Unmarshal(m, b)
}
func (m *StoreGetFeedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreGetFeedRequest.Marshal(b, m, deterministic)
}
func (m *StoreGetFeedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreGetFeedRequest.Merge(m, src)
}
func (m *StoreGetFeedRequest) XXX_Size() int {
	return xxx_messageInfo_StoreGetFeedRequest.Size(m)
}
func (m *StoreGetFeedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreGetFeedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StoreGetFeedRequest proto.InternalMessageInfo

func (m *StoreGetFeedRequest) GetFeedID() string {
	if m != nil {
		return m.FeedID
	}
	return ""
}

func (m *StoreGetFeedRequest) GetSince() int64 {
	if m != nil {
		return m.Since
	}
	return 0
}

// StoreGetFeedResponse is some articles from the store
type StoreGetFeedResponse struct {
	Articles             []*StoreArticle `protobuf:"bytes,2,rep,name=articles,proto3" json:"articles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *StoreGetFeedResponse) Reset()         { *m = StoreGetFeedResponse{} }
func (m *StoreGetFeedResponse) String() string { return proto.CompactTextString(m) }
func (*StoreGetFeedResponse) ProtoMessage()    {}
func (*StoreGetFeedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{4}
}

func (m *StoreGetFeedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreGetFeedResponse.Unmarshal(m, b)
}
func (m *StoreGetFeedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreGetFeedResponse.Marshal(b, m, deterministic)
}
func (m *StoreGetFeedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreGetFeedResponse.Merge(m, src)
}
func (m *StoreGetFeedResponse) XXX_Size() int {
	return xxx_messageInfo_StoreGetFeedResponse.Size(m)
}
func (m *StoreGetFeedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreGetFeedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StoreGetFeedResponse proto.InternalMessageInfo

func (m *StoreGetFeedResponse) GetArticles() []*StoreArticle {
	if m != nil {
		return m.Articles
	}
	return nil
}

func init() {
	proto.RegisterType((*StoreArticle)(nil), "common.StoreArticle")
	proto.RegisterType((*StorePostFeedRequest)(nil), "common.StorePostFeedRequest")
	proto.RegisterType((*StorePostFeedResponse)(nil), "common.StorePostFeedResponse")
	proto.RegisterType((*StoreGetFeedRequest)(nil), "common.StoreGetFeedRequest")
	proto.RegisterType((*StoreGetFeedResponse)(nil), "common.StoreGetFeedResponse")
}

func init() { proto.RegisterFile("store.proto", fileDescriptor_98bbca36ef968dfc) }

var fileDescriptor_98bbca36ef968dfc = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xc1, 0x4e, 0x83, 0x40,
	0x10, 0x86, 0x05, 0x0a, 0xd6, 0xa9, 0xf1, 0x30, 0xa2, 0x6e, 0x6a, 0x4d, 0xc8, 0x9e, 0x38, 0x11,
	0x53, 0x9f, 0xc0, 0xd8, 0x54, 0xb9, 0x99, 0xf5, 0xea, 0xc1, 0x16, 0xc6, 0x84, 0xa4, 0x65, 0x2b,
	0xbb, 0x1e, 0x7c, 0x15, 0x9f, 0xd6, 0x74, 0x96, 0x12, 0x69, 0x34, 0xd1, 0xdb, 0xcc, 0xfc, 0xc3,
	0x3f, 0xdf, 0x4f, 0x16, 0x46, 0xc6, 0xea, 0x86, 0xb2, 0x4d, 0xa3, 0xad, 0xc6, 0xa8, 0xd0, 0xeb,
	0xb5, 0xae, 0xe5, 0x33, 0x1c, 0x3f, 0x6d, 0xc7, 0xb7, 0x8d, 0xad, 0x8a, 0x15, 0xe1, 0x09, 0xf8,
	0xf9, 0x4c, 0x78, 0x89, 0x97, 0x1e, 0x29, 0x3f, 0x9f, 0x61, 0x0c, 0xa1, 0xad, 0xec, 0x8a, 0x84,
	0xcf, 0x23, 0xd7, 0x20, 0xc2, 0xa0, 0x5c, 0x58, 0x12, 0x41, 0xe2, 0xa5, 0x81, 0xe2, 0x7a, 0x3b,
	0x5b, 0xea, 0xf2, 0x43, 0x0c, 0x78, 0x91, 0x6b, 0xf9, 0x02, 0x31, 0xbb, 0x3f, 0x6a, 0x63, 0xe7,
	0x44, 0xa5, 0xa2, 0xb7, 0x77, 0x32, 0x16, 0xcf, 0x21, 0x7a, 0x25, 0x2a, 0xbb, 0x4b, 0x6d, 0x87,
	0xd7, 0x30, 0x5c, 0x38, 0x10, 0x23, 0xfc, 0x24, 0x48, 0x47, 0xd3, 0x38, 0x73, 0xa0, 0xd9, 0x77,
	0x4a, 0xd5, 0x6d, 0xc9, 0x0b, 0x38, 0xdb, 0xbb, 0x60, 0x36, 0xba, 0x36, 0x24, 0xef, 0xe0, 0x94,
	0x85, 0x7b, 0xfa, 0xd3, 0xe5, 0x18, 0x42, 0x53, 0xd5, 0x85, 0xcb, 0x19, 0x28, 0xd7, 0xc8, 0x87,
	0x96, 0xbf, 0x33, 0x71, 0xe6, 0xff, 0xe7, 0x9c, 0x7e, 0x7a, 0x10, 0xb2, 0x84, 0x39, 0x0c, 0x77,
	0xb0, 0x38, 0xe9, 0x7d, 0xb5, 0xf7, 0x97, 0xc6, 0x57, 0xbf, 0xa8, 0x6d, 0xc2, 0x03, 0x9c, 0xc3,
	0x61, 0x4b, 0x86, 0x97, 0xbd, 0xdd, 0x7e, 0xe8, 0xf1, 0xe4, 0x67, 0x71, 0xe7, 0xb3, 0x8c, 0xf8,
	0x4d, 0xdc, 0x7c, 0x05, 0x00, 0x00, 0xff, 0xff, 0x23, 0x21, 0x9a, 0x81, 0x22, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StoreClient is the client API for Store service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StoreClient interface {
	PostFeed(ctx context.Context, in *StorePostFeedRequest, opts ...grpc.CallOption) (*StorePostFeedResponse, error)
	GetFeed(ctx context.Context, in *StoreGetFeedRequest, opts ...grpc.CallOption) (*StoreGetFeedResponse, error)
}

type storeClient struct {
	cc *grpc.ClientConn
}

func NewStoreClient(cc *grpc.ClientConn) StoreClient {
	return &storeClient{cc}
}

func (c *storeClient) PostFeed(ctx context.Context, in *StorePostFeedRequest, opts ...grpc.CallOption) (*StorePostFeedResponse, error) {
	out := new(StorePostFeedResponse)
	err := c.cc.Invoke(ctx, "/common.Store/PostFeed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) GetFeed(ctx context.Context, in *StoreGetFeedRequest, opts ...grpc.CallOption) (*StoreGetFeedResponse, error) {
	out := new(StoreGetFeedResponse)
	err := c.cc.Invoke(ctx, "/common.Store/GetFeed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoreServer is the server API for Store service.
type StoreServer interface {
	PostFeed(context.Context, *StorePostFeedRequest) (*StorePostFeedResponse, error)
	GetFeed(context.Context, *StoreGetFeedRequest) (*StoreGetFeedResponse, error)
}

// UnimplementedStoreServer can be embedded to have forward compatible implementations.
type UnimplementedStoreServer struct {
}

func (*UnimplementedStoreServer) PostFeed(ctx context.Context, req *StorePostFeedRequest) (*StorePostFeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostFeed not implemented")
}
func (*UnimplementedStoreServer) GetFeed(ctx context.Context, req *StoreGetFeedRequest) (*StoreGetFeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFeed not implemented")
}

func RegisterStoreServer(s *grpc.Server, srv StoreServer) {
	s.RegisterService(&_Store_serviceDesc, srv)
}

func _Store_PostFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorePostFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).PostFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.Store/PostFeed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).PostFeed(ctx, req.(*StorePostFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_GetFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreGetFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).GetFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.Store/GetFeed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).GetFeed(ctx, req.(*StoreGetFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Store_serviceDesc = grpc.ServiceDesc{
	ServiceName: "common.Store",
	HandlerType: (*StoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostFeed",
			Handler:    _Store_PostFeed_Handler,
		},
		{
			MethodName: "GetFeed",
			Handler:    _Store_GetFeed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "store.proto",
}
