// Code generated by protoc-gen-go. DO NOT EDIT.
// source: store.proto

package common

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Nil struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nil) Reset()         { *m = Nil{} }
func (m *Nil) String() string { return proto.CompactTextString(m) }
func (*Nil) ProtoMessage()    {}
func (*Nil) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{0}
}

func (m *Nil) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nil.Unmarshal(m, b)
}
func (m *Nil) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nil.Marshal(b, m, deterministic)
}
func (m *Nil) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nil.Merge(m, src)
}
func (m *Nil) XXX_Size() int {
	return xxx_messageInfo_Nil.Size(m)
}
func (m *Nil) XXX_DiscardUnknown() {
	xxx_messageInfo_Nil.DiscardUnknown(m)
}

var xxx_messageInfo_Nil proto.InternalMessageInfo

type ConfigSources struct {
	Sources              []*ConfigSource `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ConfigSources) Reset()         { *m = ConfigSources{} }
func (m *ConfigSources) String() string { return proto.CompactTextString(m) }
func (*ConfigSources) ProtoMessage()    {}
func (*ConfigSources) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{1}
}

func (m *ConfigSources) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigSources.Unmarshal(m, b)
}
func (m *ConfigSources) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigSources.Marshal(b, m, deterministic)
}
func (m *ConfigSources) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigSources.Merge(m, src)
}
func (m *ConfigSources) XXX_Size() int {
	return xxx_messageInfo_ConfigSources.Size(m)
}
func (m *ConfigSources) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigSources.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigSources proto.InternalMessageInfo

func (m *ConfigSources) GetSources() []*ConfigSource {
	if m != nil {
		return m.Sources
	}
	return nil
}

type ConfigSource struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	URL                  string   `protobuf:"bytes,2,opt,name=URL,proto3" json:"URL,omitempty"`
	Store                string   `protobuf:"bytes,3,opt,name=store,proto3" json:"store,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigSource) Reset()         { *m = ConfigSource{} }
func (m *ConfigSource) String() string { return proto.CompactTextString(m) }
func (*ConfigSource) ProtoMessage()    {}
func (*ConfigSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{2}
}

func (m *ConfigSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigSource.Unmarshal(m, b)
}
func (m *ConfigSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigSource.Marshal(b, m, deterministic)
}
func (m *ConfigSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigSource.Merge(m, src)
}
func (m *ConfigSource) XXX_Size() int {
	return xxx_messageInfo_ConfigSource.Size(m)
}
func (m *ConfigSource) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigSource.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigSource proto.InternalMessageInfo

func (m *ConfigSource) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ConfigSource) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func (m *ConfigSource) GetStore() string {
	if m != nil {
		return m.Store
	}
	return ""
}

// FetchWork tells a fetcher all its jobs.
type FetchWork struct {
	Jobs                 []*FetchJob `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *FetchWork) Reset()         { *m = FetchWork{} }
func (m *FetchWork) String() string { return proto.CompactTextString(m) }
func (*FetchWork) ProtoMessage()    {}
func (*FetchWork) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{3}
}

func (m *FetchWork) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchWork.Unmarshal(m, b)
}
func (m *FetchWork) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchWork.Marshal(b, m, deterministic)
}
func (m *FetchWork) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchWork.Merge(m, src)
}
func (m *FetchWork) XXX_Size() int {
	return xxx_messageInfo_FetchWork.Size(m)
}
func (m *FetchWork) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchWork.DiscardUnknown(m)
}

var xxx_messageInfo_FetchWork proto.InternalMessageInfo

func (m *FetchWork) GetJobs() []*FetchJob {
	if m != nil {
		return m.Jobs
	}
	return nil
}

// FetchJob tells a fetcher to do something.
type FetchJob struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	URL                  string   `protobuf:"bytes,2,opt,name=URL,proto3" json:"URL,omitempty"`
	Store                string   `protobuf:"bytes,3,opt,name=store,proto3" json:"store,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchJob) Reset()         { *m = FetchJob{} }
func (m *FetchJob) String() string { return proto.CompactTextString(m) }
func (*FetchJob) ProtoMessage()    {}
func (*FetchJob) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{4}
}

func (m *FetchJob) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchJob.Unmarshal(m, b)
}
func (m *FetchJob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchJob.Marshal(b, m, deterministic)
}
func (m *FetchJob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchJob.Merge(m, src)
}
func (m *FetchJob) XXX_Size() int {
	return xxx_messageInfo_FetchJob.Size(m)
}
func (m *FetchJob) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchJob.DiscardUnknown(m)
}

var xxx_messageInfo_FetchJob proto.InternalMessageInfo

func (m *FetchJob) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *FetchJob) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func (m *FetchJob) GetStore() string {
	if m != nil {
		return m.Store
	}
	return ""
}

type StoreArticle struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Date                 int64    `protobuf:"varint,3,opt,name=date,proto3" json:"date,omitempty"`
	Body                 string   `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreArticle) Reset()         { *m = StoreArticle{} }
func (m *StoreArticle) String() string { return proto.CompactTextString(m) }
func (*StoreArticle) ProtoMessage()    {}
func (*StoreArticle) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{5}
}

func (m *StoreArticle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreArticle.Unmarshal(m, b)
}
func (m *StoreArticle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreArticle.Marshal(b, m, deterministic)
}
func (m *StoreArticle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreArticle.Merge(m, src)
}
func (m *StoreArticle) XXX_Size() int {
	return xxx_messageInfo_StoreArticle.Size(m)
}
func (m *StoreArticle) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreArticle.DiscardUnknown(m)
}

var xxx_messageInfo_StoreArticle proto.InternalMessageInfo

func (m *StoreArticle) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *StoreArticle) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *StoreArticle) GetDate() int64 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *StoreArticle) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type StorePostFeedRequest struct {
	FeedID               string          `protobuf:"bytes,1,opt,name=feedID,proto3" json:"feedID,omitempty"`
	Articles             []*StoreArticle `protobuf:"bytes,2,rep,name=articles,proto3" json:"articles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *StorePostFeedRequest) Reset()         { *m = StorePostFeedRequest{} }
func (m *StorePostFeedRequest) String() string { return proto.CompactTextString(m) }
func (*StorePostFeedRequest) ProtoMessage()    {}
func (*StorePostFeedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{6}
}

func (m *StorePostFeedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorePostFeedRequest.Unmarshal(m, b)
}
func (m *StorePostFeedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorePostFeedRequest.Marshal(b, m, deterministic)
}
func (m *StorePostFeedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorePostFeedRequest.Merge(m, src)
}
func (m *StorePostFeedRequest) XXX_Size() int {
	return xxx_messageInfo_StorePostFeedRequest.Size(m)
}
func (m *StorePostFeedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StorePostFeedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StorePostFeedRequest proto.InternalMessageInfo

func (m *StorePostFeedRequest) GetFeedID() string {
	if m != nil {
		return m.FeedID
	}
	return ""
}

func (m *StorePostFeedRequest) GetArticles() []*StoreArticle {
	if m != nil {
		return m.Articles
	}
	return nil
}

type StorePostFeedResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorePostFeedResponse) Reset()         { *m = StorePostFeedResponse{} }
func (m *StorePostFeedResponse) String() string { return proto.CompactTextString(m) }
func (*StorePostFeedResponse) ProtoMessage()    {}
func (*StorePostFeedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{7}
}

func (m *StorePostFeedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorePostFeedResponse.Unmarshal(m, b)
}
func (m *StorePostFeedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorePostFeedResponse.Marshal(b, m, deterministic)
}
func (m *StorePostFeedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorePostFeedResponse.Merge(m, src)
}
func (m *StorePostFeedResponse) XXX_Size() int {
	return xxx_messageInfo_StorePostFeedResponse.Size(m)
}
func (m *StorePostFeedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StorePostFeedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StorePostFeedResponse proto.InternalMessageInfo

type StoreGetFeedRequest struct {
	FeedID               string   `protobuf:"bytes,1,opt,name=feedID,proto3" json:"feedID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreGetFeedRequest) Reset()         { *m = StoreGetFeedRequest{} }
func (m *StoreGetFeedRequest) String() string { return proto.CompactTextString(m) }
func (*StoreGetFeedRequest) ProtoMessage()    {}
func (*StoreGetFeedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{8}
}

func (m *StoreGetFeedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreGetFeedRequest.Unmarshal(m, b)
}
func (m *StoreGetFeedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreGetFeedRequest.Marshal(b, m, deterministic)
}
func (m *StoreGetFeedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreGetFeedRequest.Merge(m, src)
}
func (m *StoreGetFeedRequest) XXX_Size() int {
	return xxx_messageInfo_StoreGetFeedRequest.Size(m)
}
func (m *StoreGetFeedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreGetFeedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StoreGetFeedRequest proto.InternalMessageInfo

func (m *StoreGetFeedRequest) GetFeedID() string {
	if m != nil {
		return m.FeedID
	}
	return ""
}

type StoreGetFeedResponse struct {
	Articles             []*StoreArticle `protobuf:"bytes,2,rep,name=articles,proto3" json:"articles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *StoreGetFeedResponse) Reset()         { *m = StoreGetFeedResponse{} }
func (m *StoreGetFeedResponse) String() string { return proto.CompactTextString(m) }
func (*StoreGetFeedResponse) ProtoMessage()    {}
func (*StoreGetFeedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{9}
}

func (m *StoreGetFeedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreGetFeedResponse.Unmarshal(m, b)
}
func (m *StoreGetFeedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreGetFeedResponse.Marshal(b, m, deterministic)
}
func (m *StoreGetFeedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreGetFeedResponse.Merge(m, src)
}
func (m *StoreGetFeedResponse) XXX_Size() int {
	return xxx_messageInfo_StoreGetFeedResponse.Size(m)
}
func (m *StoreGetFeedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreGetFeedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StoreGetFeedResponse proto.InternalMessageInfo

func (m *StoreGetFeedResponse) GetArticles() []*StoreArticle {
	if m != nil {
		return m.Articles
	}
	return nil
}

func init() {
	proto.RegisterType((*Nil)(nil), "common.Nil")
	proto.RegisterType((*ConfigSources)(nil), "common.ConfigSources")
	proto.RegisterType((*ConfigSource)(nil), "common.ConfigSource")
	proto.RegisterType((*FetchWork)(nil), "common.FetchWork")
	proto.RegisterType((*FetchJob)(nil), "common.FetchJob")
	proto.RegisterType((*StoreArticle)(nil), "common.StoreArticle")
	proto.RegisterType((*StorePostFeedRequest)(nil), "common.StorePostFeedRequest")
	proto.RegisterType((*StorePostFeedResponse)(nil), "common.StorePostFeedResponse")
	proto.RegisterType((*StoreGetFeedRequest)(nil), "common.StoreGetFeedRequest")
	proto.RegisterType((*StoreGetFeedResponse)(nil), "common.StoreGetFeedResponse")
}

func init() { proto.RegisterFile("store.proto", fileDescriptor_98bbca36ef968dfc) }

var fileDescriptor_98bbca36ef968dfc = []byte{
	// 399 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0x51, 0x4f, 0xe2, 0x40,
	0x10, 0xc7, 0x69, 0x4b, 0x0b, 0x0c, 0xdc, 0x85, 0xdb, 0x2b, 0x77, 0x0d, 0xc7, 0x25, 0x64, 0x73,
	0x0f, 0x24, 0x97, 0x6b, 0xee, 0x7a, 0x1f, 0xc0, 0xa8, 0xa4, 0x88, 0x31, 0xc4, 0x94, 0x18, 0x5f,
	0x7c, 0x90, 0xb6, 0x8b, 0x56, 0x0b, 0x8b, 0xdd, 0xe5, 0xc1, 0xaf, 0xe2, 0xa7, 0x35, 0xdd, 0xed,
	0x12, 0x8a, 0x98, 0xa8, 0x6f, 0xb3, 0x33, 0xff, 0xf9, 0xcf, 0x2f, 0x93, 0x59, 0x68, 0x32, 0x4e,
	0x33, 0xe2, 0xae, 0x32, 0xca, 0x29, 0xb2, 0x22, 0xba, 0x58, 0xd0, 0x25, 0x36, 0xc1, 0x98, 0x24,
	0x29, 0x3e, 0x80, 0x4f, 0xc7, 0x74, 0x39, 0x4f, 0x6e, 0xa6, 0x74, 0x9d, 0x45, 0x84, 0x21, 0x17,
	0x6a, 0x4c, 0x86, 0x8e, 0xd6, 0x37, 0x06, 0x4d, 0xcf, 0x76, 0x65, 0x87, 0xbb, 0xad, 0x0b, 0x94,
	0x08, 0xfb, 0xd0, 0xda, 0x2e, 0xa0, 0xcf, 0xa0, 0x8f, 0x87, 0x8e, 0xd6, 0xd7, 0x06, 0x8d, 0x40,
	0x1f, 0x0f, 0x51, 0x1b, 0x8c, 0x8b, 0xe0, 0xcc, 0xd1, 0x45, 0x22, 0x0f, 0x91, 0x0d, 0xa6, 0x00,
	0x72, 0x0c, 0x91, 0x93, 0x0f, 0xfc, 0x0f, 0x1a, 0x3e, 0xe1, 0xd1, 0xed, 0x25, 0xcd, 0xee, 0xd1,
	0x2f, 0xa8, 0xde, 0xd1, 0x50, 0x11, 0xb4, 0x15, 0x81, 0x10, 0x9c, 0xd2, 0x30, 0x10, 0x55, 0x7c,
	0x04, 0x75, 0x95, 0xf9, 0xf0, 0xd8, 0x2b, 0x68, 0x4d, 0xf3, 0xe0, 0x30, 0xe3, 0x49, 0x94, 0xbe,
	0xc4, 0xb7, 0xc1, 0xe4, 0x09, 0x4f, 0x49, 0xe1, 0x24, 0x1f, 0x08, 0x41, 0x35, 0x9e, 0x71, 0x69,
	0x65, 0x04, 0x22, 0xce, 0x73, 0x21, 0x8d, 0x1f, 0x9d, 0xaa, 0x10, 0x8a, 0x18, 0x5f, 0x83, 0x2d,
	0xdc, 0xcf, 0x29, 0xe3, 0x3e, 0x21, 0x71, 0x40, 0x1e, 0xd6, 0x84, 0x71, 0xf4, 0x0d, 0xac, 0x39,
	0x21, 0xf1, 0x66, 0x52, 0xf1, 0x42, 0x7f, 0xa1, 0x3e, 0x93, 0x20, 0xcc, 0xd1, 0xcb, 0xdb, 0xdf,
	0xa6, 0x0c, 0x36, 0x2a, 0xfc, 0x1d, 0x3a, 0x3b, 0x13, 0xd8, 0x8a, 0x2e, 0x19, 0xc1, 0x7f, 0xe0,
	0xab, 0x28, 0x8c, 0xc8, 0x5b, 0x26, 0xe3, 0x93, 0x82, 0x74, 0x23, 0x97, 0x36, 0xef, 0x27, 0xf2,
	0x12, 0xb0, 0xe4, 0x41, 0x20, 0x0f, 0x60, 0x44, 0xb8, 0x3a, 0xac, 0xa6, 0xea, 0x9b, 0x24, 0x69,
	0xb7, 0xb3, 0xef, 0xa8, 0x18, 0xae, 0xa0, 0xdf, 0x50, 0x1b, 0x11, 0x2e, 0x8e, 0xa0, 0xd4, 0xf0,
	0xa5, 0x74, 0x03, 0x79, 0x1d, 0x57, 0xbc, 0x27, 0x0d, 0x4c, 0x41, 0x81, 0xc6, 0x50, 0x57, 0x1b,
	0x40, 0xbd, 0x12, 0xe0, 0xce, 0xea, 0xbb, 0x3f, 0x5f, 0xa9, 0x16, 0x6b, 0xab, 0x20, 0x5f, 0x10,
	0x08, 0xa7, 0x1f, 0x25, 0x6d, 0x79, 0x93, 0xdd, 0xde, 0xfe, 0xa2, 0xf2, 0x09, 0x2d, 0xf1, 0xdf,
	0xfe, 0x3f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x22, 0x49, 0x3b, 0xdb, 0x7e, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ConfigClient is the client API for Config service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConfigClient interface {
	GetSources(ctx context.Context, in *Nil, opts ...grpc.CallOption) (*ConfigSources, error)
	GetWork(ctx context.Context, in *Nil, opts ...grpc.CallOption) (*FetchWork, error)
}

type configClient struct {
	cc *grpc.ClientConn
}

func NewConfigClient(cc *grpc.ClientConn) ConfigClient {
	return &configClient{cc}
}

func (c *configClient) GetSources(ctx context.Context, in *Nil, opts ...grpc.CallOption) (*ConfigSources, error) {
	out := new(ConfigSources)
	err := c.cc.Invoke(ctx, "/common.Config/GetSources", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configClient) GetWork(ctx context.Context, in *Nil, opts ...grpc.CallOption) (*FetchWork, error) {
	out := new(FetchWork)
	err := c.cc.Invoke(ctx, "/common.Config/GetWork", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigServer is the server API for Config service.
type ConfigServer interface {
	GetSources(context.Context, *Nil) (*ConfigSources, error)
	GetWork(context.Context, *Nil) (*FetchWork, error)
}

// UnimplementedConfigServer can be embedded to have forward compatible implementations.
type UnimplementedConfigServer struct {
}

func (*UnimplementedConfigServer) GetSources(ctx context.Context, req *Nil) (*ConfigSources, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSources not implemented")
}
func (*UnimplementedConfigServer) GetWork(ctx context.Context, req *Nil) (*FetchWork, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWork not implemented")
}

func RegisterConfigServer(s *grpc.Server, srv ConfigServer) {
	s.RegisterService(&_Config_serviceDesc, srv)
}

func _Config_GetSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Nil)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServer).GetSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.Config/GetSources",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServer).GetSources(ctx, req.(*Nil))
	}
	return interceptor(ctx, in, info, handler)
}

func _Config_GetWork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Nil)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServer).GetWork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.Config/GetWork",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServer).GetWork(ctx, req.(*Nil))
	}
	return interceptor(ctx, in, info, handler)
}

var _Config_serviceDesc = grpc.ServiceDesc{
	ServiceName: "common.Config",
	HandlerType: (*ConfigServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSources",
			Handler:    _Config_GetSources_Handler,
		},
		{
			MethodName: "GetWork",
			Handler:    _Config_GetWork_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "store.proto",
}

// StoreClient is the client API for Store service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StoreClient interface {
	PostFeed(ctx context.Context, in *StorePostFeedRequest, opts ...grpc.CallOption) (*StorePostFeedResponse, error)
	GetFeed(ctx context.Context, in *StoreGetFeedRequest, opts ...grpc.CallOption) (*StoreGetFeedResponse, error)
}

type storeClient struct {
	cc *grpc.ClientConn
}

func NewStoreClient(cc *grpc.ClientConn) StoreClient {
	return &storeClient{cc}
}

func (c *storeClient) PostFeed(ctx context.Context, in *StorePostFeedRequest, opts ...grpc.CallOption) (*StorePostFeedResponse, error) {
	out := new(StorePostFeedResponse)
	err := c.cc.Invoke(ctx, "/common.Store/PostFeed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) GetFeed(ctx context.Context, in *StoreGetFeedRequest, opts ...grpc.CallOption) (*StoreGetFeedResponse, error) {
	out := new(StoreGetFeedResponse)
	err := c.cc.Invoke(ctx, "/common.Store/GetFeed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoreServer is the server API for Store service.
type StoreServer interface {
	PostFeed(context.Context, *StorePostFeedRequest) (*StorePostFeedResponse, error)
	GetFeed(context.Context, *StoreGetFeedRequest) (*StoreGetFeedResponse, error)
}

// UnimplementedStoreServer can be embedded to have forward compatible implementations.
type UnimplementedStoreServer struct {
}

func (*UnimplementedStoreServer) PostFeed(ctx context.Context, req *StorePostFeedRequest) (*StorePostFeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostFeed not implemented")
}
func (*UnimplementedStoreServer) GetFeed(ctx context.Context, req *StoreGetFeedRequest) (*StoreGetFeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFeed not implemented")
}

func RegisterStoreServer(s *grpc.Server, srv StoreServer) {
	s.RegisterService(&_Store_serviceDesc, srv)
}

func _Store_PostFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorePostFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).PostFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.Store/PostFeed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).PostFeed(ctx, req.(*StorePostFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_GetFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreGetFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).GetFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.Store/GetFeed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).GetFeed(ctx, req.(*StoreGetFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Store_serviceDesc = grpc.ServiceDesc{
	ServiceName: "common.Store",
	HandlerType: (*StoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostFeed",
			Handler:    _Store_PostFeed_Handler,
		},
		{
			MethodName: "GetFeed",
			Handler:    _Store_GetFeed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "store.proto",
}
