name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v1.0.0
      with:
        go-version: 1.13
    - name: Checkout
      uses: actions/checkout@v1
    - name: Make
      run: make app
